/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalTakedownRouteImport } from './routes/legal.takedown'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalAcceptableUseRouteImport } from './routes/legal.acceptable-use'
import { Route as AuthenticatedVideoRouteImport } from './routes/_authenticated.video'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated.library'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated.home'
import { Route as AuthenticatedFaceswapRouteImport } from './routes/_authenticated.faceswap'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated.create'
import { Route as AuthenticatedBodyswapRouteImport } from './routes/_authenticated.bodyswap'
import { Route as ApiPublicReportRouteImport } from './routes/api/public/report'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTakedownRoute = LegalTakedownRouteImport.update({
  id: '/legal/takedown',
  path: '/legal/takedown',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAcceptableUseRoute = LegalAcceptableUseRouteImport.update({
  id: '/legal/acceptable-use',
  path: '/legal/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVideoRoute = AuthenticatedVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFaceswapRoute = AuthenticatedFaceswapRouteImport.update({
  id: '/faceswap',
  path: '/faceswap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBodyswapRoute = AuthenticatedBodyswapRouteImport.update({
  id: '/bodyswap',
  path: '/bodyswap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicReportRoute = ApiPublicReportRouteImport.update({
  id: '/api/public/report',
  path: '/api/public/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bodyswap': typeof AuthenticatedBodyswapRoute
  '/create': typeof AuthenticatedCreateRoute
  '/faceswap': typeof AuthenticatedFaceswapRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/video': typeof AuthenticatedVideoRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/takedown': typeof LegalTakedownRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/report': typeof ApiPublicReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bodyswap': typeof AuthenticatedBodyswapRoute
  '/create': typeof AuthenticatedCreateRoute
  '/faceswap': typeof AuthenticatedFaceswapRoute
  '/home': typeof AuthenticatedHomeRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/video': typeof AuthenticatedVideoRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/takedown': typeof LegalTakedownRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/report': typeof ApiPublicReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/bodyswap': typeof AuthenticatedBodyswapRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/faceswap': typeof AuthenticatedFaceswapRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/video': typeof AuthenticatedVideoRoute
  '/legal/acceptable-use': typeof LegalAcceptableUseRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/takedown': typeof LegalTakedownRoute
  '/legal/terms': typeof LegalTermsRoute
  '/api/public/report': typeof ApiPublicReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/report'
    | '/reset-password'
    | '/signup'
    | '/bodyswap'
    | '/create'
    | '/faceswap'
    | '/home'
    | '/library'
    | '/profile'
    | '/video'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/takedown'
    | '/legal/terms'
    | '/api/public/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/report'
    | '/reset-password'
    | '/signup'
    | '/bodyswap'
    | '/create'
    | '/faceswap'
    | '/home'
    | '/library'
    | '/profile'
    | '/video'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/takedown'
    | '/legal/terms'
    | '/api/public/report'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/report'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/bodyswap'
    | '/_authenticated/create'
    | '/_authenticated/faceswap'
    | '/_authenticated/home'
    | '/_authenticated/library'
    | '/_authenticated/profile'
    | '/_authenticated/video'
    | '/legal/acceptable-use'
    | '/legal/privacy'
    | '/legal/takedown'
    | '/legal/terms'
    | '/api/public/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  LegalAcceptableUseRoute: typeof LegalAcceptableUseRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTakedownRoute: typeof LegalTakedownRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiPublicReportRoute: typeof ApiPublicReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/takedown': {
      id: '/legal/takedown'
      path: '/legal/takedown'
      fullPath: '/legal/takedown'
      preLoaderRoute: typeof LegalTakedownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/acceptable-use': {
      id: '/legal/acceptable-use'
      path: '/legal/acceptable-use'
      fullPath: '/legal/acceptable-use'
      preLoaderRoute: typeof LegalAcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/video': {
      id: '/_authenticated/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof AuthenticatedVideoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/faceswap': {
      id: '/_authenticated/faceswap'
      path: '/faceswap'
      fullPath: '/faceswap'
      preLoaderRoute: typeof AuthenticatedFaceswapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bodyswap': {
      id: '/_authenticated/bodyswap'
      path: '/bodyswap'
      fullPath: '/bodyswap'
      preLoaderRoute: typeof AuthenticatedBodyswapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/report': {
      id: '/api/public/report'
      path: '/api/public/report'
      fullPath: '/api/public/report'
      preLoaderRoute: typeof ApiPublicReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBodyswapRoute: typeof AuthenticatedBodyswapRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedFaceswapRoute: typeof AuthenticatedFaceswapRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVideoRoute: typeof AuthenticatedVideoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBodyswapRoute: AuthenticatedBodyswapRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedFaceswapRoute: AuthenticatedFaceswapRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVideoRoute: AuthenticatedVideoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  LegalAcceptableUseRoute: LegalAcceptableUseRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTakedownRoute: LegalTakedownRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiPublicReportRoute: ApiPublicReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
